version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "Qwerty123!"
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "127.0.0.1:5432:5432"

  gotubebot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: gotubebot
      TOKEN: ${TOKEN}
      POSTGRES: ${POSTGRES}
    depends_on:
      - postgres
    # restart: always