name: Release

on: 
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'main'

jobs:
  build:
    name: Make build
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Insall system dependences
        run: sudo apt-get install -y "$PACKAGES"
        env:
          PACKAGES: tar
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install go dependences
        run: go mod tidy
      - name: Build project
        run: go build -ldflags="$LDFLAGS" -o "$APP" cmd/main/main.go
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
          LDFLAGS: "-w -s"
          APP: ${{github.event.repository.name}}
      - name: Make release tar
        run: tar -cvzf ${{github.event.repository.name}}.tgz "$FILES"
        env:
          FILES: ${{github.event.repository.name}}
      - name: Set tag name for release
        run: echo "GITHUB_RELEASE_TAG=$(date +v%m.%d.%H.%M)" >> $GITHUB_ENV

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_RELEASE_TAG }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.event.repository.name }}.tgz
          asset_name: ${{ github.event.repository.name }}.tgz
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
